---
abstract: 'A second generation publish/subscribe component for the POE framework'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
build_requires:
  POE: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-PubSub
requires:
  Carp: 0
  Moose: 0
  MooseX::Declare: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  POE::API::Peek: 0
  POEx::Role::SessionInstantiation: 0
  POEx::Types: 0
  Sub::Exporter: 0
  aliased: 0
  constant: 0
resources:
  repository: git://github.com/nperez/pcps.git
version: 1.100910
